version: '3'
services:
  db:
    image: postgres
    env_file: .env.development  # Load environment variables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.dev.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the development SQL script
    ports:
      - '5432:5432'
volumes:
  pgdata:
