# Use a lightweight Node image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Copy the rest of the application code
COPY . .

# Expose the application's port
EXPOSE 3000

# Define the command to run the app
CMD ["node", "dist/index.js"]
